---
abstract: 'run blocking functions asynchronously by forking'
author:
  - 'Joel Berger <joel.a.berger@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.42, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojo-IOLoop-ForkCall
provides:
  Mojo::IOLoop::ForkCall:
    file: lib/Mojo/IOLoop/ForkCall.pm
    version: 0.01
requires:
  Child: 0
  Child::IPC::Pipely: 0
  Mojolicious: 4.0
resources:
  bugtracker: https://github.com/jberger/Mojo-IOLoop-ForkCall/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/jberger/Mojo-IOLoop-ForkCall
version: 0.01
